---
# tasks file for mongodb
- name: "Instala Mongodb no servidor"
  apt:
    name: mongodb
    state: present
    update_cache: yes

- name: "Ajusta mongodb.conf"
  replace:
    path: /etc/mongodb.conf
    regexp: 'bind_ip = 127.0.0.1'
    replace: 'bind_ip = 0.0.0.0'
    backup: yes
  notify:
    - inicia mongodb

- name: "Instala docker"
  apt:
    name: docker.io
    state: present
  notify:
    - inicia docker

- name: Install docker python module
  pip:
    name: docker

- name: Criar o container do mongodb express
  docker_container:
    name: mongoexpress
    image: mongo-express:0.54.0
    state: started
    network_mode: host      
    ports:
      - '8081:8081'
    env: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: "{{ user_mongo }}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "{{ pass_mongo }}"
      ME_CONFIG_MONGODB_SERVER: 127.0.0.1
